version: 2.1

defaults: &defaults {
  docker:
    - image: circleci/node:8
}

jobs:
  build:
    <<: *defaults  
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run: 
          name: update-yarn
          command: yarn
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules
      - run:
          name: build
          command: yarn build
#   deploy:
#     <<: *defaults  

# workflows:
#   version: 2
#   build-deploy:
#     jobs:
#       - build:
#           filters:
#             tags:
#               only: